# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  phpVersion: 7.2

stages:
  - stage: Build
    displayName: Build stage
    jobs:

      # Build variables: https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables
      - job: Build
        displayName: Build Job
        steps:
        - script: |
            sudo update-alternatives --set php /usr/bin/php$(phpVersion)
            sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
            sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
            sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
            sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
            php -version
          displayName: 'Use PHP version $(phpVersion)'

        - script: composer install --no-interaction --prefer-dist
          displayName: 'composer install'

        - script: cat /etc/os-release
          displayName: 'display current OS on build machine'

        - task: ArchiveFiles@2
          displayName: 'Archive "Archive files'
          inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            replaceExistingArchive: true

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    jobs:
      # Job directories on VM
      # https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/jobdirectories.md
      - deployment: VMDeploy
        displayName: Web deploy
        environment:
          resourceType: VirtualMachine
          name: zzz-test-environment
          resourceName: zzz-azure-pipeline-test
        strategy:
          runOnce:
            preDeploy:
              steps:
              # - task: DownloadPipelineArtifact@2
              - script: |
                  sudo apt update -y
                  sudo apt install unzip file -y
                displayName: Install build dependencies
            # Deployment steps automatically downloads build artifact.
            deploy:
              steps:
              - checkout: self
              - script: |
                  echo "Agent Workfolder: $(Agent.WorkFolder)"
                  echo "Environment.Name: $(Environment.Name)"
                  echo "Environment.Id $(Environment.Id)"
                  echo "Environment.ResourceName: $(Environment.ResourceName)"
                  echo "Environment.ResourceId: $(Environment.ResourceId)"
                  echo "Strategy.Name: $(Strategy.Name)"
                  echo "Strategy.CycleName: $(Strategy.CycleName)"
                  echo "-------------"
                  artifact_name="drop"
                  artifact_path="$(Agent.WorkFolder)/$(Environment.Id)/${artifact_name}/$(Build.BuildId).zip"
                  echo "Artifact path: ${artifact_path}"
                displayName: Show Azure Devops variables
              - script: |
                  artifact_name="drop"
                  artifact_path="$(Agent.WorkFolder)/$(Environment.Id)/${artifact_name}/$(Build.BuildId).zip"
                  target_path="$(Agent.WorkFolder)/$(Environment.Id)/b/$(Build.BuildId)"
                  unzip "${artifact_path}" -d "${target_path}"
                displayName: Unzip build artifact
              - script: echo my first deployment
              - script: cat /etc/os-release
              - script: ls -la
